"""Realtime (audio-to-audio) runtime primitives.

Provider-neutral contracts (:data:`RealtimeEvent`, :class:`RealtimeConfig`,
:class:`RealtimeClient`), the upstream :class:`LiveInputQueue`, and the Gemini Live
provider client. Provider SDK imports are lazy, so importing this package never pulls
the ``realtime`` optional dependency.
"""

from .base import (
    AgentChangedEvent,
    AudioDeltaEvent,
    ErrorEvent,
    GoAwayEvent,
    InputTranscriptEvent,
    InterruptedEvent,
    OutputTranscriptEvent,
    RealtimeClient,
    RealtimeConfig,
    RealtimeEvent,
    ReconnectConfig,
    SessionUpdateEvent,
    ToolCallEvent,
    ToolResultEvent,
    TurnCompleteEvent,
    VADConfig,
)
from .events import (
    HandoffEvent,
    InterruptEvent,
    InterruptResume,
    ItemStreamDelta,
    ItemStreamEnd,
    ItemStreamStart,
    RealtimeEventBroadcaster,
    RealtimeEventQueue,
    RealtimeEventStream,
    RealtimeEventType,
    ToolApprovalRequest,
    ToolApprovalResponse,
    broadcast_handoff,
    broadcast_item_stream_delta,
    broadcast_tool_approval,
    create_handoff,
    create_interrupt,
    create_interrupt_resume,
    create_item_stream_delta,
    create_item_stream_end,
    create_item_stream_start,
    create_tool_approval_request,
    create_tool_approval_response,
    get_global_broadcaster,
)
from .handoffs import RealtimeHandoff
from .providers.gemini_live import GeminiLiveClient, normalize_message
from .queue import LiveInput, LiveInputKind, LiveInputQueue
from .tool_filtering import RealtimeToolFilter


__all__ = [
    "AgentChangedEvent",
    "AudioDeltaEvent",
    "ErrorEvent",
    "GeminiLiveClient",
    "GoAwayEvent",
    "HandoffEvent",
    "InputTranscriptEvent",
    "InterruptEvent",
    "InterruptResume",
    "InterruptedEvent",
    "ItemStreamDelta",
    "ItemStreamEnd",
    "ItemStreamStart",
    "LiveInput",
    "LiveInputKind",
    "LiveInputQueue",
    "OutputTranscriptEvent",
    "RealtimeClient",
    "RealtimeConfig",
    "RealtimeEvent",
    "RealtimeEventBroadcaster",
    "RealtimeEventQueue",
    "RealtimeEventStream",
    "RealtimeEventType",
    "RealtimeHandoff",
    "RealtimeToolFilter",
    "ReconnectConfig",
    "SessionUpdateEvent",
    "ToolApprovalRequest",
    "ToolApprovalResponse",
    "ToolCallEvent",
    "ToolResultEvent",
    "TurnCompleteEvent",
    "VADConfig",
    "broadcast_handoff",
    "broadcast_item_stream_delta",
    "broadcast_tool_approval",
    "create_handoff",
    "create_interrupt",
    "create_interrupt_resume",
    "create_item_stream_delta",
    "create_item_stream_end",
    "create_item_stream_start",
    "create_tool_approval_request",
    "create_tool_approval_response",
    "get_global_broadcaster",
    "normalize_message",
]
