{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "alcyoneus.fullname" . }}-api
  labels:
    {{- include "alcyoneus.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "alcyoneus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "alcyoneus.fullname" . }}-worker
  labels:
    {{- include "alcyoneus.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "alcyoneus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}