"""Interactive project scaffolding for Alcyoneus OS."""

from __future__ import annotations

from pathlib import Path


def _get_default_model(provider: str) -> str:
    if provider == "gemini":
        return "gemini-2.5-flash"
    elif provider == "anthropic":
        return "claude-3-5-sonnet-latest"
    elif provider == "ollama":
        return "llama3.2"
    return "gpt-4o-mini"


def generate_agent_code(
    project_name: str,
    agent_type: str,
    storage: str,
    llm_provider: str,
) -> str:
    """Generate agent.py code based on architecture, storage, and provider."""
    lines = [
        '"""',
        f"{project_name} - Generated by Alcyoneus CLI",
        f"Architecture: {agent_type}",
        f"Storage: {storage}",
        f"Provider: {llm_provider}",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]

    # Imports based on storage
    if storage == "sqlite":
        lines.append("from alcyoneus.storage.checkpointer import SqliteCheckpointer")
    elif storage == "postgres":
        lines.append("from alcyoneus.storage.checkpointer import PgCheckpointer")
    elif storage == "qdrant":
        lines.append("from alcyoneus.storage.store.qdrant_store import QdrantStore")
    else:
        lines.append("from alcyoneus.storage.checkpointer import InMemoryCheckpointer")

    model_name = _get_default_model(llm_provider)

    # Imports based on agent type
    if agent_type == "react":
        lines.extend([
            "from alcyoneus.prebuilt.agent import ReactAgent",
            "from alcyoneus.prebuilt.tools import safe_calculator, fetch_url, web_search",
            "",
            "def create_agent():",
            "    tools = [safe_calculator, fetch_url, web_search]",
            "    agent = ReactAgent(",
            f'        model="{model_name}",',
            '        system_prompt="You are a helpful, rigorous enterprise assistant with access to tools.",',
            "        tools=tools,",
            "    )",
            "    return agent",
        ])
    elif agent_type == "plan-act-reflect":
        lines.extend([
            "from alcyoneus.prebuilt.agent.plan_act_reflect import PlanActReflectAgent",
            "from alcyoneus.prebuilt.tools import safe_calculator, fetch_url",
            "",
            "def create_agent():",
            "    tools = [safe_calculator, fetch_url]",
            "    agent = PlanActReflectAgent(",
            f'        model="{model_name}",',
            "        tools=tools,",
            "    )",
            "    return agent",
        ])
    elif agent_type == "rag":
        lines.extend([
            "from alcyoneus.prebuilt.agent import RAGAgent",
            "from alcyoneus.storage.store import InMemoryStore",
            "",
            "def create_agent():",
            "    store = InMemoryStore()",
            "    agent = RAGAgent(",
            f'        model="{model_name}",',
            '        system_prompt="You are a domain-expert answering questions using retrieved context.",',
            "        store=store,",
            "    )",
            "    return agent",
        ])
    elif agent_type == "swarm":
        lines.extend([
            "from alcyoneus.prebuilt.agent import SwarmAgent",
            "",
            "def create_agent():",
            "    agent = SwarmAgent(",
            f'        model="{model_name}",',
            '        system_prompt="You are a swarm coordinator routing tasks across specialized agents.",',
            "    )",
            "    return agent",
        ])
    elif agent_type == "supervisor":
        lines.extend([
            "from alcyoneus.prebuilt.agent import SupervisorTeamAgent",
            "",
            "def create_agent():",
            "    agent = SupervisorTeamAgent(",
            '        name="supervisor",',
            f'        model="{model_name}",',
            '        system_prompt="You coordinate a specialist team to deliver complete solutions.",',
            "        team_members={",
            f'            "researcher": {{"model": "{model_name}", "prompt": "Research specialist"}},',
            f'            "analyst": {{"model": "{model_name}", "prompt": "Data analysis specialist"}},',
            "        },",
            "    )",
            "    return agent",
        ])
    else:  # fallback
        lines.extend([
            "from alcyoneus.prebuilt.agent import ReactAgent",
            "from alcyoneus.prebuilt.tools import safe_calculator",
            "",
            "def create_agent():",
            f'    return ReactAgent(model="{model_name}", tools=[safe_calculator])',
        ])

    lines.extend([
        "",
        'if __name__ == "__main__":',
        "    agent = create_agent()",
        '    print(f"Agent initialized: {agent}")',
    ])
    return "\n".join(lines) + "\n"


def generate_pyproject_toml(project_name: str, storage: str, llm_provider: str) -> str:
    """Generate pyproject.toml tailored to project requirements."""
    deps = ['"alcyoneus>=1.1.0"', '"pytest>=8.0.0"', '"pytest-asyncio>=0.23.0"']
    if llm_provider == "gemini":
        deps.append('"google-genai>=1.56.0"')
    elif llm_provider == "openai":
        deps.append('"openai>=1.77.0"')

    if storage == "postgres":
        deps.extend(['"asyncpg>=0.29.0"', '"redis>=4.2"'])
    elif storage == "qdrant":
        deps.append('"qdrant-client>=1.7.0"')

    deps_str = ",\n    ".join(deps)

    return f"""[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{project_name}"
version = "0.1.0"
description = "Agentic workflow powered by Alcyoneus OS"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    {deps_str}
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
"""


def generate_env_example(storage: str, llm_provider: str) -> str:
    """Generate .env.example with relevant API keys and config."""
    lines = ["# Environment Configuration for Alcyoneus Agent", ""]
    if llm_provider == "openai":
        lines.append("OPENAI_API_KEY=your-openai-api-key-here")
    elif llm_provider == "gemini":
        lines.append("GEMINI_API_KEY=your-gemini-api-key-here")
    elif llm_provider == "anthropic":
        lines.append("ANTHROPIC_API_KEY=your-anthropic-api-key-here")
    elif llm_provider == "ollama":
        lines.append("OLLAMA_BASE_URL=http://localhost:11434")

    if storage == "postgres":
        lines.extend([
            "POSTGRES_URL=postgresql://user:password@localhost:5432/alcyoneus_db",
            "REDIS_URL=redis://localhost:6379/0",
        ])
    elif storage == "qdrant":
        lines.extend([
            "QDRANT_URL=http://localhost:6333",
            "# QDRANT_API_KEY=your-qdrant-cloud-key",
        ])
    return "\n".join(lines) + "\n"


def generate_test_file(project_name: str, agent_type: str) -> str:
    """Generate test_agent.py pre-configured for pytest."""
    return f'''"""Automated unit tests for {project_name}."""

import pytest
from agent import create_agent


def test_agent_creation():
    """Verify agent initializes with proper config and tools."""
    agent = create_agent()
    assert agent is not None


@pytest.mark.asyncio
async def test_agent_execution_mock():
    """Ensure agent interface is callable."""
    agent = create_agent()
    assert hasattr(agent, "ainvoke") or hasattr(agent, "execute") or hasattr(agent, "compile")
'''


def generate_readme(project_name: str, agent_type: str, storage: str, llm_provider: str) -> str:
    """Generate README.md for the new project."""
    return f"""# {project_name}

An enterprise agentic application built with **[Alcyoneus OS](https://github.com/alcyoneus-os/alcyoneus)**.

## Architecture
- **Agent Pattern**: `{agent_type}`
- **Storage Checkpointer**: `{storage}`
- **LLM Provider**: `{llm_provider}`

## Quickstart

1. **Install dependencies**:
   ```bash
   pip install -e .
   ```

2. **Configure environment**:
   ```bash
   cp .env.example .env
   # Edit .env with your credentials
   ```

3. **Run tests**:
   ```bash
   pytest
   ```

4. **Launch Agent**:
   ```bash
   python agent.py
   ```
"""


def scaffold_project(
    target_dir: Path,
    project_name: str,
    agent_type: str = "react",
    storage: str = "memory",
    llm_provider: str = "openai",
) -> list[Path]:
    """Scaffold full project directory with all boilerplate files."""
    target_dir.mkdir(parents=True, exist_ok=True)
    (target_dir / "tests").mkdir(exist_ok=True)

    created_files: list[Path] = []

    # 1. agent.py
    agent_file = target_dir / "agent.py"
    agent_file.write_text(generate_agent_code(project_name, agent_type, storage, llm_provider))
    created_files.append(agent_file)

    # 2. pyproject.toml
    pyproject_file = target_dir / "pyproject.toml"
    pyproject_file.write_text(generate_pyproject_toml(project_name, storage, llm_provider))
    created_files.append(pyproject_file)

    # 3. .env.example
    env_file = target_dir / ".env.example"
    env_file.write_text(generate_env_example(storage, llm_provider))
    created_files.append(env_file)

    # 4. tests/test_agent.py
    test_file = target_dir / "tests" / "test_agent.py"
    test_file.write_text(generate_test_file(project_name, agent_type))
    created_files.append(test_file)

    # 5. README.md
    readme_file = target_dir / "README.md"
    readme_file.write_text(generate_readme(project_name, agent_type, storage, llm_provider))
    created_files.append(readme_file)

    return created_files
